services:
  creature-vis-training:
    build:
      context: ../../src/training/
      dockerfile: ../../docker/training/Dockerfile
      args:
        - BUILDPLATFORM=linux/arm64
        - TARGETARCH=arm64
    image: training:local
    platform: linux/arm64
    ports:
      - "8080:8080"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - TRAINING_BUCKET=creature-vision-training-set
      - BATCH_SIZE=16
      - GOOGLE_CLOUD_PROJECT=creature-vision
      - CLOUD_LOCATION=us-east1
      - MODEL_BUCKET=tf_models_cv
      - BASE_MODEL_PATH=gs://tf_models_cv/v1_Feb_15_2025/v1_Feb_15_2025.keras
      - AIP_TENSORBOARD_LOG_DIR=gs://creture-vision-ml-artifacts/local
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G

