services:
  dog-prediction-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDPLATFORM=linux/amd64
        - TARGETARCH=amd64
    image: gcr.io/${PROJECT_ID}/dog-prediction-app:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      - PORT=8080
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
    depends_on:
      tfserving:
        condition: service_healthy