version: '3.8'

services:
  dog-prediction-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDPLATFORM=linux/arm64
        - TARGETARCH=arm64
    image: dog-prediction-app:local
    platform: linux/arm64
    ports:
      - "8080:8080"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

