{
 "title": "Creature Vision App",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "model_version",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Top Misclassified Dog Breeds $model_version",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "project": "creature-vision",
     "rawSql": "select count(actual) as actual_count, actual from `creature-vision.dog_prediction_app.prediction_metrics`\nwhere is_correct = false\nand model_version = '${model_version}'\ngroup by actual\norder by actual_count desc\nLIMIT 25;\n"
    }
   ]
  },
  {
   "title": "Lifetime Prediction Accuracy - ${model_version}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "creature-vision",
     "rawSql": "SELECT\n  AVG(CAST(is_correct AS INT64)) AS avg_prediction_accuracy\nFROM\n  `dog_prediction_app.prediction_metrics`\nWHERE model_version = '${model_version}'"
    }
   ]
  },
  {
   "title": "\"Prediction Accuracy - Model Version: ${model_version}\"",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "dog_prediction_app",
     "project": "creature-vision",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(timestamp, HOUR) AS time_bucket,\n  AVG(CAST(is_correct AS INT64)) AS accuracy\nFROM\n  `dog_prediction_app.prediction_metrics`\nWHERE\n  timestamp BETWEEN TIMESTAMP('${__from:date}') AND TIMESTAMP('${__to:date}')\n  and model_version = '${model_version}'\nGROUP BY\n  time_bucket\nORDER BY\n  time_bucket"
    }
   ]
  }
 ]
}