services:
  dog-prediction-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDPLATFORM=linux/amd64
        - TARGETARCH=amd64
        - MODEL_VERSION=${VERSION}
    image: creature-vision/dog-prediction-app:${VERSION}
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      - PORT=8080
      - MODEL_VERSION=${VERSION}
