apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  GF_AUTH_DISABLE_LOGIN_FORM: "true"
  GF_INSTALL_PLUGINS: "grafana-bigquery-datasource"
