# inference-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-inference
  template:
    metadata:
      labels:
        app: model-inference
    spec:
      serviceAccountName: vertex-k8s-sa
      containers:
      - name: inference
        image: gcr.io/${PROJECT_ID}/inference:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: model-inference
spec:
  selector:
    app: model-inference
  ports:
  - port: 8080
    targetPort: 8080
