# service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vertex-k8s-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: vertex-sa@creature-vision.iam.gserviceaccount.com